### ISSUE TITLE
modules/unitframes/layout/layout.lua:1805: attempt to index field 'player' (a nil value)

### ISSUE THREAD

**Issue by Pahn1988** [FireSiku/LUI#21] opened 2022-10-28 20:37 UTC
[string "@Interface/AddOns/LUI/modules/unitframes/layout/layout.lua"]:1805: in function AlternativePower'
[string "@Interface/AddOns/LUI/modules/unitframes/layout/layout.lua"]:2603: in function styleFunc'
[string "@Interface/AddOns/LUI/api/oUF11/ouf.lua"]:331: in function <Interface/AddOns/LUI/api/oUF11/ouf.lua:259>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/LUI/api/oUF11/ouf.lua"]:737: in function Spawn'
[string "@Interface/AddOns/LUI/modules/unitframes/options/toggle.lua"]:79: in function ?'
[string "@Interface/AddOns/LUI/modules/unitframes/options/toggle.lua"]:54: in function ToggleUnit'
[string "@Interface/AddOns/LUI/modules/unitframes/unitframes_init.lua"]:1859: in function <...ce/AddOns/LUI/modules/unitframes/unitframes_init.lua:1857>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by Pahn1988** [comment] 2022-11-01 13:55
1x ...face/AddOns/LUI/modules/unitframes/layout/layout.lua:1827: attempt to index field 'player' (a nil value)
[string "@Interface/AddOns/LUI/modules/unitframes/layout/layout.lua"]:1827: in function `AlternativePower'
[string "@Interface/AddOns/LUI/modules/unitframes/options/toggle.lua"]:927: in function `ApplySettings'
[string "@Interface/AddOns/LUI/modules/unitframes/options/toggle.lua"]:1035: in function `Refresh'
[string "@Interface/AddOns/LUIOptions/LUIOptions.lua"]:117: in function <Interface/AddOns/LUIOptions/LUIOptions.lua:111>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:827: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:649>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...ns/Ace3/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

**Comment by FireSiku** [comment] 2022-11-04 06:00
Got this one down. It was caused by 9 instances where module.db.player should've been module.db.profile.player
Fixed in Alpha 18

**Closed by FireSiku** 2022-11-04 06:00 UTC
Labels: bug, Unitframes
